name: Cache Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-61dd842

      - name: prime-cache-61dd842
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      - name: Install dependencies
        run: |
          npm install || true
